
name: open_neopixel_controller
main: main.py
build_dir: _build_neopixel

frozen:
  - platform/utils
  - platform/led/neopixel.py
  - platform/led/status.py
  - platform/sensor/ambient.py
  - platform/btn/setup.py

packages:
  - deps/tinyweb/tinyweb
  - deps/tinydns/tinydns
  - deps/tinymqtt/tinymqtt

micropython-lib:
  - uasyncio
  - uasyncio.core
  - uasyncio.synchro
  - logging

# Temporary commented out until new UI landed
# filesystems:
#   /web:
#     ui-vuetify: ui/devices/open_neopixel_controller
#     readonly: true
#     gzip: true

#   /data:
#     files:
#       - config.yaml
#     reserved: 10000
